"""empty message

Revision ID: 326bc5746c72
Revises: 
Create Date: 2020-12-21 18:54:14.382188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '326bc5746c72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('car_make', sa.String(), nullable=False),
    sa.Column('car_color', sa.String(), nullable=False),
    sa.Column('car_state', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('car_id')
    )
    op.drop_table('student')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('student_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('student_id', name='student_pkey')
    )
    op.drop_table('car')
    # ### end Alembic commands ###
